apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecraftserverfleets.shulkermc.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: shulker-system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
