apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: limbo
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  template:
    spec:
      tags:
        - limbo
      version:
        channel: Paper
        name: '1.19.3'
      config: {}
