comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default: {}
      shulker-sdk-bindings-rust:
        flags:
          - shulker-sdk-bindings-rust
      google-agones-crds:
        flags:
          - google-agones-crds
      shulker-kube-utils:
        flags:
          - shulker-kube-utils
      shulker-operator:
        flags:
          - shulker-operator
      shulker-utils:
        flags:
          - shulker-utils
      shulker-crds:
        flags:
          - shulker-crds
flags:
  shulker-sdk-bindings-rust:
    paths:
      - packages/shulker-sdk/bindings/rust
    carryforward: true
  google-agones-crds:
    paths:
      - packages/google-agones-crds
    carryforward: true
  shulker-kube-utils:
    paths:
      - packages/shulker-kube-utils
    carryforward: true
  shulker-operator:
    paths:
      - packages/shulker-operator
    carryforward: true
  shulker-utils:
    paths:
      - packages/shulker-utils
    carryforward: true
  shulker-crds:
    paths:
      - packages/shulker-crds
    carryforward: true
