apiVersion: v1
kind: Pod
metadata:
  name: public-7c5cf8c5fc-pocxwc-test
  namespace: shulker-test
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: public-7c5cf8c5fc-pocxwc
    app.kubernetes.io/name: public
    minecraftcluster.shulkermc.io/name: getting-started
    proxydeployment.shulkermc.io/name: public
spec:
  volumes:
    - name: shulker-config
      configMap:
        name: public-config
        defaultMode: 420
    - name: shulker-forwarding-secret
      secret:
        secretName: getting-started-forwarding-secret
        defaultMode: 420
    - name: proxy-data
      emptyDir: {}
    - name: proxy-drain-lock
      emptyDir: {}
    - name: proxy-tmp
      emptyDir: {}
  initContainers:
    - name: init-fs
      image: alpine:latest
      command:
        - sh
        - /mnt/shulker/config/init-fs.sh
      env:
        - name: SHULKER_CONFIG_DIR
          value: /mnt/shulker/config
        - name: PROXY_DATA_DIR
          value: /server
        - name: TYPE
          value: VELOCITY
        - name: SHULKER_PROXY_AGENT_VERSION
          value: 0.0.1
        - name: PROXY_PLUGIN_URLS
        - name: PROXY_PATCH_URLS
      resources: {}
      volumeMounts:
        - name: shulker-config
          readOnly: true
          mountPath: /mnt/shulker/config
        - name: proxy-data
          mountPath: /server
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  containers:
    - name: proxy
      image: itzg/bungeecord:latest
      ports:
        - name: minecraft
          containerPort: 25577
          protocol: TCP
      env:
        - name: SHULKER_PROXY_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SHULKER_PROXY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SHULKER_PROXY_TTL_SECONDS
          value: '86400'
        - name: TYPE
          value: VELOCITY
        - name: VELOCITY_BUILD_ID
          value: latest
      volumeMounts:
        - name: shulker-forwarding-secret
          readOnly: true
          mountPath: /mnt/shulker/forwarding-secret
        - name: proxy-data
          mountPath: /server
        - name: proxy-drain-lock
          readOnly: true
          mountPath: /mnt/drain-lock
        - name: proxy-tmp
          mountPath: /tmp
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  serviceAccountName: getting-started-proxy
