# permissions for end users to edit minecraftservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserver-editor-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/status
  verbs:
  - get
