# permissions for end users to view minecraftclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftcluster-viewer-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters/status
  verbs:
  - get
