# permissions for end users to edit minecraftserverdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserverdeployment-editor-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments/status
  verbs:
  - get
