# permissions for end users to view minecraftserverdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserverdeployment-viewer-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftserverdeployments/status
  verbs:
  - get
