# permissions for end users to view proxydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxydeployment-viewer-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments/status
  verbs:
  - get
