---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters/pool
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - proxydeployments/status
  verbs:
  - get
  - patch
  - update
