
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - templateresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - templateresources/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - templateresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - shulkermc.io
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
