apiVersion: apps/v1
kind: Deployment
metadata:
  name: shulker-operator
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: shulker-operator
    app.kubernetes.io/component: shulker-operator
    app.kubernetes.io/part-of: shulker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: shulker-operator
      app.kubernetes.io/instance: shulker-operator
      app.kubernetes.io/component: shulker-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shulker-operator
        app.kubernetes.io/instance: shulker-operator
        app.kubernetes.io/component: shulker-operator
    spec:
      containers:
        - name: shulker-operator
          image: ghcr.io/jeremylvln/shulker-operator
          imagePullPolicy: Always
          args:
            - --metrics-bind-address=0.0.0.0:8080
            - --api-bind-address=0.0.0.0:9090
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
            - containerPort: 9090
              protocol: TCP
              name: api
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - 'ALL'
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: arm64
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: shulker-operator
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: devops.jeremylvln.fr/arm-only
          operator: 'Equal'
          value: 'true'
          effect: 'NoSchedule'
