apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shulker
    app.kubernetes.io/part-of: shulker
    app.kubernetes.io/managed-by: kustomize
  name: operator
  namespace: system
