apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shulker-system

resources:
  - ../../resources/crd
  - ../../resources/components/shulker-operator
  - ../../resources/components/shulker-operator/prometheus

images:
  - name: ghcr.io/jeremylvln/shulker-operator
    newTag: 0.3.0
