apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shulker-operator:leader-election
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: shulker-operator-leader-election
    app.kubernetes.io/component: shulker-operator-rbac
    app.kubernetes.io/part-of: shulker
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - shulker-operator.shulkermc.io
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
