apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/shulkermc.io_minecraftclusters.yaml
  - bases/shulkermc.io_proxyfleets.yaml
  - bases/shulkermc.io_minecraftservers.yaml
  - bases/shulkermc.io_minecraftserverfleets.yaml
