name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-operator:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/iamblueslime/shulker-operator:latest
          cache-from: type=registry,ref=ghcr.io/iamblueslime/shulker-operator:latest
          cache-to: type=inline
